name: implcate order
favicon: null
layout_spectrum: 0.059743016958236694
typography_spectrum: 0.6337505695410073
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.4077213096898049
  lightness: 0.35005112760700285
  saturation: 0.3328647599555552
  rhythmicContrast: 0.361126353032887
purpose: []
