name: implcate order
favicon: null
layout_spectrum: 0.38695
typography_spectrum: 0.8197
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262d33'
    - '#00000a'
    - '#70837d'
    - '#004e87'
    - '#485d72'
  brandStrength: 0.4077213096898049
  lightness: 0.35005112760700285
  saturation: 0.3328647599555552
  rhythmicContrast: 0.361126353032887
purpose: []
